//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto01_ApiPagamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public string NumeroCartao { get; set; }
        public string NomeCliente { get; set; }
        public double Limite { get; set; }
    }
}
